mobile/src/pages/order/addOrder/addOrder.tsx
mobile/src/pages/order/editOrder/editOrder.tsx
mobile/src/pages/users/add-user/AddUser.tsx
mobile/src/pages/users/edit-user/EditUser.tsx
mobile/src/utils/isInvalidText.ts

Issue: #https://github.com/5sControl/5s-frontend/issues/928

fix: user register errors

---

mobile/src/pages/directories-dynamic/CollectionItemDynamic.tsx

Issue: #https://github.com/5sControl/5s-frontend/issues/938

fix: collection item translations

---

mobile/src/App.tsx
mobile/src/pages/reports/fullReport/FullReport.tsx

#Issue: https://github.com/5sControl/5s-frontend/issues/927

add: order information reports

---

mobile/src/pages/users/edit-user/EditUser.tsx

#Issue: https://github.com/5sControl/5s-frontend/issues/931
Fix for comment

fix: add hide password btn

---

mobile/src/components/header/Header.scss
mobile/src/components/header/Header.tsx

Issue: https://github.com/5sControl/5s-frontend/issues/935

fix: header title padding

---

mobile/src/pages/menu/Menu.scss
mobile/src/pages/menu/Menu.tsx

#Issue: https://github.com/5sControl/5s-frontend/issues/948

feat: add version

---

mobile/src/pages/directories-dynamic/CollectionCreateDynamic.tsx
mobile/src/pages/directories-dynamic/CollectionUpdateDynamic.tsx

#Issue: https://github.com/5sControl/5s-frontend/issues/934
#Issue: https://github.com/5sControl/5s-frontend/issues/707

fix: add confirmation modal for directories

---

mobile/src/pages/reports/Reports.tsx

#Issue: https://github.com/5sControl/5s-frontend/issues/973

fix: report date reset

---

mobile/src/pages/order/addOrder/addOrder.tsx

#Issue: https://github.com/5sControl/5s-frontend/issues/913

fix: order name max length

---

mobile/src/pages/menu/Menu.tsx

#Issue: https://github.com/5sControl/5s-frontend/issues/974

fix: account loading

---

mobile/src/components/inputs/inputReadonly/inputReadonly.scss
mobile/src/components/inputs/inputReadonly/inputReadonly.tsx

#Issue: https://github.com/5sControl/5s-frontend/issues/935

fix: readonly input overflow

---

mobile/src/pages/directories-dynamic/CollectionItemDynamic.tsx

#Issue: https://github.com/5sControl/5s-frontend/issues/962

fix: delete modal collection name

---

mobile/src/api/orders.ts

Hot fix for bug for url duplicating after building

fix: orders api

---

mobile/src/store/dynamicApiSlice.ts

#Issue: https://github.com/5sControl/5s-frontend/issues/992

fix: change dynamic api queries to mutations

---

mobile/src/pages/order/editOrder/editOrder.tsx

#Issue: https://github.com/5sControl/5s-frontend/issues/913

fix: remove order name max length on edit

---

src/pages/camera/modal/zones/zoneList/zoneList.jsx

#Issue: https://github.com/5sControl/5s-frontend/issues/902#issuecomment-2606425802

fix: zones names sort

---

mobile/src/pages/order/orderItem/orderItem.tsx
mobile/src/pages/timespan/editTimespan/editTimespan.tsx

#Issue: https://github.com/5sControl/5s-frontend/issues/1011

fix: blank operations navigation

---

mobile/src/models/interfaces/orders.interface.ts
mobile/src/pages/timespan/editTimespan/editTimespan.tsx

#Issue: https://github.com/5sControl/5s-frontend/issues/1015

fix: edit timespan employee name

---

mobile/src/dispatcher/index.ts
mobile/src/pages/timespan/newTimespan/newTimespan.tsx

#Issue: https://github.com/5sControl/5s-frontend/issues/1011#issuecomment-2609334708

fix: add order item name to header

---

mobile/src/pages/timespan/newTimespan/newTimespan.tsx

#Issue: https://github.com/5sControl/5s-frontend/issues/1016#issuecomment-2611692318

fix: timespans default value

---

mobile/src/pages/timespan/newTimespan/newTimespan.tsx
mobile/src/utils/parseInputDate.ts

#Issue: https://github.com/5sControl/5s-frontend/issues/1027

fix: date format and navigation

---

mobile/src/pages/scanner/Scanner.tsx
mobile/src/pages/timespan/newTimespan/newTimespan.tsx
mobile/src/store/timespanSlice.ts

#Issue: https://github.com/5sControl/5s-frontend/issues/1033

fix: new timespan header title

---

mobile/src/pages/timespan/camera/TimespanCameras.tsx

#Issue: https://github.com/5sControl/5s-frontend/issues/1037

fix: timespan camera back navigation

---

mobile/src/locales/en/translation.json
mobile/src/locales/pl/translation.json
mobile/src/locales/ru/translation.json
mobile/src/models/interfaces/employee.interface.ts
mobile/src/pages/users/add-user/AddUser.tsx
mobile/src/pages/users/edit-user/EditUser.tsx
mobile/src/pages/users/user/User.tsx
mobile/src/utils/isValidEmail.ts

#Issue: https://github.com/5sControl/5s-frontend/issues/1028

feat: add email for employees

---

mobile/src/pages/users/add-user/AddUser.tsx
mobile/src/pages/users/edit-user/EditUser.tsx

#Issue: https://github.com/5sControl/5s-frontend/issues/1048

fix: edit employee modals

---

mobile/src/pages/menu/Menu.tsx
mobile/src/pages/tasks/employeeTasks/EmployeeTasks.tsx

#Issue: https://github.com/5sControl/5s-frontend/issues/1002

feat: add timespans for worker

---

src/pages/OrdersViewD3/components/operation.jsx

#Issue: https://github.com/5sControl/5s-frontend/issues/1044

fix: show video list

---

mobile/src/pages/ordersView/operationDetail/operationDetail.tsx

#Issue: https://github.com/5sControl/5s-frontend/issues/1037#issuecomment-2648130948

fix: operation detail back navigation
